# Generated by Django 5.1 on 2024-09-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_flashsale',
            field=models.BooleanField(default=False),
        ),
    ]
